### ISSUE TITLE
.fff files created with split_seqs have error in data field

### ISSUE THREAD

**Issue by ayazlali** [LJMUAstroecology/flirpy#103]
I was able to decode my .seq file and could see the images in the preview folder.  However, the .tiff files are all black and when I used Fff() to open one of the generated .fff files variable explorer shows an error in the data field: ```**ERROR**: a bytes-like object is required, not 'str'```. When I run split_seqs it ends with this error: ```ValueError: buffer is smaller than requested size``` on ```\flirpy\io\fff.py", line 194, in get_image
    self.image = np.frombuffer(
                 ^^^^^^^^^^^^^^```, but it does generate the preview jpgs files fine.
Here is the complete log when I run ```split_seqs```:
```
(flirenv) PS C:\Users\AYAZlALI\Documents\flirpy-main> py .\scripts\split_seqs -i C:\Users\AYAZlALI\Documents\Flir_files\300mV_200mHz_22ohm-0020.seq
INFO:__main__:Loading: C:\Users\AYAZlALI\Documents\Flir_files\300mV_200mHz_22ohm-0020.seq
INFO:flirpy.io.seq:Splitting 1 files
  0%|                                                                                                | 0/1 [00:00<?, ?it/s]INFO:flirpy.io.seq:Splitting C:\Users\AYAZlALI\Documents\Flir_files\300mV_200mHz_22ohm-0020.seq into C:\Users\AYAZlALI\Documents\flirpy-main\300mV_200mHz_22ohm-0020
100%|██████████████████████████████████████████████████████████████████████████████████▊| 594/595 [00:04<00:00, 136.12it/s]
  0%|                                                                                                | 0/1 [00:04<?, ?it/s]
Traceback (most recent call last):
  File "C:\Users\AYAZlALI\Documents\flirpy-main\scripts\split_seqs", line 112, in <module>
    folders = splitter.process(files)
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\AYAZlALI\AppData\Local\anaconda3\envs\flirenv\Lib\site-packages\flirpy\io\seq.py", line 151, in process
    self._process_seq(seq, folder)
  File "C:\Users\AYAZlALI\AppData\Local\anaconda3\envs\flirenv\Lib\site-packages\flirpy\io\seq.py", line 279, in _process_seq
    image = frame.get_radiometric_image(meta=meta)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\AYAZlALI\AppData\Local\anaconda3\envs\flirenv\Lib\site-packages\flirpy\io\fff.py", line 180, in get_radiometric_image
    image = raw2temp(self.get_image(), self.meta)
                     ^^^^^^^^^^^^^^^^
  File "C:\Users\AYAZlALI\AppData\Local\anaconda3\envs\flirenv\Lib\site-packages\flirpy\io\fff.py", line 194, in get_image
    self.image = np.frombuffer(
                 ^^^^^^^^^^^^^^
ValueError: buffer is smaller than requested size
```

**Comment by jveitchmichaelis** [comment]
Please try installing the latest version from github (0.4) and see if that fixes the issue. Thanks!

**Comment by ayazlali** [comment]
Thank you, @jveitchmichaelis ! I installed the latest version in a new environment and still had the same issue. Edited the original post to include the issue template. I hope this helps with diagnosing the problem and thanks a lot for your support.

**Comment by jveitchmichaelis** [comment]
Hmm, if you're willing to send me a copy of the SEQ file I'd be happy to take a look (you can email me a link if it's sensitive).

Maybe flirpy isn't correctly determining the frame size, are you able to check if it's correct? Do you get a black image that's the correct size(?) - or perhaps the splitter creates the image but doesn't fill it with data because it crashes.

Are you able to extract data using the `Seq` API - without using the splitter script? It's possible the script needs to be updated.

**Comment by ayazlali** [comment]
I was able to extract the images from the .seq file with the FLIR science file sdk, so I think my file is OK. The file is not sensitive, it's just the video of a resistor, I will try to attach it to the original post. How would I use the .seq API? I was going to figure out what it does by modifying the script. Is there an easier way to learn how the API works?

**Comment by jveitchmichaelis** [comment]
Thanks for this and sorry for the delay, I'll check out the file you've uploaded!

**Comment by jveitchmichaelis** [comment]
OK I think this is (finally) fixed and probably fixes some other issues too. There were two sort of related problems. The main one was that the FFF magic header can appear inside images (it's not escaped) so the dumb iterator that looks for frames would get the wrong file offsets. This is fixed by adding a parser that walks the file and properly checks record lengths. The other is some robustness around big/little endian files, which I've also now fixed.

If you're happy, do you mind if I take a frame from your data to include as a test file? It's a good endianness case.

**Comment by jveitchmichaelis** [comment]
The TIFF being black is not a bug, it's just scaled in radiometric values and normal image viewers won't show you the range of values well. If you plot it with matplotlib and a colormap, you'll see the resistor you were testing (it'll look like the previews).

**Comment by jveitchmichaelis** [comment]
<img width="1095" height="606" alt="Image" src="https://github.com/user-attachments/assets/638c0ce8-83fa-4e95-9e66-8ffef9e95b2d" />
